### PR TITLE
Perform write to cassandra asynchronously

### LINKED ISSUE #12: Write Asynchronously to Cassandra
The kafka streams thread should not block in order to write new traces to cassandra but use the async methods already provided by the driver.

### PR DESCRIPTION
**Pull request by lotzk**
Fixes #12 by performing all writes (inserting new traces) to the cassandra database asynchronously.

### CODE REVIEW

**Comment by lotzk** [comment]
Beware that the tests are still flaky. Unfortunately, I did not fix this on its own but in https://github.com/ExplorViz/trace-service/pull/11.

**Comment by Alexander-Krause-Glau** [comment]
@lotzk Not sure if flaky or always failing.

**Comment by lotzk** [comment]
My bad, some test were indeed failing. Should be working now.

**Review by Alexander-Krause-Glau — APPROVED** [review]
Nice, works. Thank you.

**Pull request merged**
